### ISSUE TITLE
Update kubefwd to 1.18.1

### ISSUE THREAD

**Issue by Panthaaaa** [txn2/homebrew-tap#2]
As kubefwd was updated to 1.18.1 and fixed a serious issue with AKS token refreshes (thanks for fixing that!), but the brew tap is still on the 1.18.0 version.

**Comment by danielhoherd** [comment]
This can be closed.
- <https://github.com/txn2/homebrew-tap/blob/master/Formula/kubefwd.rb#L8>
- <https://github.com/txn2/homebrew-tap/commits/master/Formula/kubefwd.rb>
- <https://github.com/txn2/homebrew-tap/compare/d6c0bca3bb8..master#diff-f137be87fa99b1f4a7a1495eee48b46b897553502cdd8c6d310c66be3cd03fee>
